/*
 홍길동, 860824-1655068    XuXfYvPwSxcaOOkFr7nKxA==
 김둘리, 921108-1582816    7C/JeeKz9lV+cMdsEIL+vw==
 마징가, 880601-2455116    ETSazzN0fdyZvBRow2+J5A==
 베지터, 910411-1656116    NqAxseg6FWumlSLIHenusQ==
 손오공, 820326-2715702    WeWmO1Sct0KHnN3g9tvU9w==
*/


/* 회원가입이 가능한 사람 */
INSERT INTO SIGN_ABLE_USER (ID, USER_NM, REG_NO) values (1, '홍길동','XuXfYvPwSxcaOOkFr7nKxA==');
INSERT INTO SIGN_ABLE_USER (ID, USER_NM, REG_NO) values (2, '김둘리','7C/JeeKz9lV+cMdsEIL+vw==');
INSERT INTO SIGN_ABLE_USER (ID, USER_NM, REG_NO) values (3, '마징가','ETSazzN0fdyZvBRow2+J5A==');
INSERT INTO SIGN_ABLE_USER (ID, USER_NM, REG_NO) values (4, '베지터','NqAxseg6FWumlSLIHenusQ==');
INSERT INTO SIGN_ABLE_USER (ID, USER_NM, REG_NO) values (5, '손오공','WeWmO1Sct0KHnN3g9tvU9w==');

INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_USER');

--
-- /* 직원 정보 */
-- INSERT INTO EMPLOYEE (EMPLOYEE_ID, MEMBER_KEY, COMPANY_ID,
--                        PAY_DT, JOIN_DT, RETIRE_DT)
-- VALUES (1, 1, 1, PARSEDATETIME('2020-11-02', 'yyyy-MM-dd'),
--         PARSEDATETIME('2020-10-02', 'yyyy-MM-dd'), PARSEDATETIME('2021-11-02', 'yyyy-MM-dd')
--         );
--
--
-- /* 소득관련 테이블 */
-- INSERT INTO INCOME (INCOME_ID, MEMBER_KEY, COMPANY_ID,
--                       INCOME_DETAILS_INFO_ID, INCOME_SEPARATE_INFO_ID, INCOME_AMT)
-- VALUES (1, 1, 1, 1, 1, '30000000');
--
-- /* 소득내역 코드&정보 */
-- INSERT INTO INCOME_DETAILS_INFO (INCOME_DETAILS_INFO_ID, INCOME_DETAILS_CD
--                                     , INCOME_DETAILS_NM)
-- VALUES (1, 'A1', '급여');
--
-- /* 소득구분 코드&정보 */
-- INSERT INTO INCOME_SEPARATE_INFO (INCOME_SEPARATE_INFO_ID, INCOME_SEPARATE_CD, INCOME_SEPARATE_NM, INCOME_SEPARATE_TYPE)
-- VALUES (1, 'B1', '근로소득 (연간)','P');
-- INSERT INTO INCOME_SEPARATE_INFO (INCOME_SEPARATE_INFO_ID, INCOME_SEPARATE_CD, INCOME_SEPARATE_NM, INCOME_SEPARATE_TYPE)
-- VALUES (2, 'B2', '보험료','S');
-- INSERT INTO INCOME_SEPARATE_INFO (INCOME_SEPARATE_INFO_ID, INCOME_SEPARATE_CD, INCOME_SEPARATE_NM, INCOME_SEPARATE_TYPE)
-- VALUES (3, 'B3', '교육비','S');
-- INSERT INTO INCOME_SEPARATE_INFO (INCOME_SEPARATE_INFO_ID, INCOME_SEPARATE_CD, INCOME_SEPARATE_NM, INCOME_SEPARATE_TYPE)
-- VALUES (4, 'B4', '기부금','S');
-- INSERT INTO INCOME_SEPARATE_INFO (INCOME_SEPARATE_INFO_ID, INCOME_SEPARATE_CD, INCOME_SEPARATE_NM, INCOME_SEPARATE_TYPE)
-- VALUES (5, 'B5', '의료비','S');
-- INSERT INTO INCOME_SEPARATE_INFO (INCOME_SEPARATE_INFO_ID, INCOME_SEPARATE_CD, INCOME_SEPARATE_NM, INCOME_SEPARATE_TYPE)
-- VALUES (6, 'Z1', '퇴직연금','A');
--
-- /* 회사 정보 */
-- INSERT INTO COMPANY (COMPANY_ID, COMPANY_CD, COMPANY_NAME, CORPORATE_REGISTRATION_NO)
-- VALUES (1, 'CO001', '(주)활빈당', '012-34-56789');
--
-- /* 소득공제 */
-- INSERT INTO INCOME_DEDUCTION (INCOME_DEDUCTION_ID, MEMBER_KEY, INCOME_SEPARATE_INFO_ID, INCOME_DEDUCTION_AMT)
-- VALUES (1, 1, 2, '100000');
--
-- INSERT INTO INCOME_DEDUCTION (INCOME_DEDUCTION_ID, MEMBER_KEY, INCOME_SEPARATE_INFO_ID, INCOME_DEDUCTION_AMT)
-- VALUES (2, 1, 3, '200000');
--
-- INSERT INTO INCOME_DEDUCTION (INCOME_DEDUCTION_ID, MEMBER_KEY, INCOME_SEPARATE_INFO_ID, INCOME_DEDUCTION_AMT)
-- VALUES (3, 1, 4, '150000');
--
-- INSERT INTO INCOME_DEDUCTION (INCOME_DEDUCTION_ID, MEMBER_KEY, INCOME_SEPARATE_INFO_ID, INCOME_DEDUCTION_AMT)
-- VALUES (4, 1, 5, '700000');
--
-- INSERT INTO INCOME_DEDUCTION (INCOME_DEDUCTION_ID, MEMBER_KEY, INCOME_SEPARATE_INFO_ID, INCOME_DEDUCTION_AMT)
-- VALUES (5, 1, 6, '1333333.333');
--
-- /* 세금 */
-- INSERT INTO TAX (TAX_ID, MEMBER_KEY, CALCULATED_TAX_AMT)
-- VALUES (1, 1, '600000');
--
-- /* 앱 정보 */
-- INSERT INTO APP_INFO (APP_INFO_ID, APP_VER, PRODUCTION_COMPANY_NM, APP_SVC_CD, APP_HOST_NM,
--                        WORKER_RES_DT,
--                        WORKER_REQ_DT)
-- VALUES (1, '2021112501', '삼쩜삼', 'test01', 'jobis-codetest',
--         PARSEDATETIME('2022-08-16 06:27:35.160789', 'yyyy-MM-dd HH:mm:ss.nnnnnn'),
--         PARSEDATETIME('2022-08-16 06:27:35.160851', 'yyyy-MM-dd HH:mm:ss.nnnnnn')
--         );
--

