//DROP TABLE IF EXISTS `MEMBER`;
DROP TABLE IF EXISTS `SIGN_ABLE_USER`;
DROP TABLE IF EXISTS `TAX`;
DROP TABLE IF EXISTS `INCOME_SEPARATE_INFO`;
DROP TABLE IF EXISTS `INCOME_DETAILS_INFO`;
DROP TABLE IF EXISTS `INCOME_DEDUCTION`;
DROP TABLE IF EXISTS `INCOME`;
DROP TABLE IF EXISTS `EMPLOYEE`;
DROP TABLE IF EXISTS `COMPANY`;
DROP TABLE IF EXISTS `APP_INFO`;

-- CREATE TABLE `MEMBER`
-- (
--     `MEMBER_KEY`            bigint              NOT NULL GENERATED BY DEFAULT AS IDENTITY,
--     `MEMBER_ID`             varchar(30)         NOT NULL,
--     `PASSWORD`              varchar(300)        NOT NULL,
--     `MEMBER_NM`             varchar(30)         NOT NULL,
--     `REG_NO`                varchar(300)        NOT NULL,
--     `CREATE_DT`             date                NOT NULL,
--     `LAST_MODIFY_DT`        date                NOT NULL,
--     PRIMARY KEY (`MEMBER_KEY`)
-- );

CREATE TABLE `SIGN_ABLE_USER`
(
    `ID`        bigint              NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `USER_NM`   varchar(30)         NOT NULL,
    `REG_NO`    varchar(300)        NOT NULL,
    PRIMARY KEY (`ID`)
);
--
-- CREATE TABLE `TAX`
-- (
--     `TAX_ID`                bigint          NOT NULL    GENERATED BY DEFAULT AS IDENTITY,
--     `MEMBER_ID`             bigint          NOT NULL,
--     `CALCULATED_TAX_AMT`    varchar(100),
--     PRIMARY KEY (`TAX_ID`)
-- );
--
-- CREATE TABLE `INCOME_SEPARATE_INFO`
-- (
--     `INCOME_SEPARATE_INFO_ID`   bigint      NOT NULL    GENERATED BY DEFAULT AS IDENTITY,
--     `INCOME_SEPARATE_CD`        varchar(30),
--     `INCOME_SEPARATE_NM`        varchar(30),
--     `INCOME_SEPARATE_TYPE`      varchar(30),
--     PRIMARY KEY (`INCOME_SEPARATE_INFO_ID`)
-- );
--
-- CREATE TABLE `INCOME_DETAILS_INFO`
-- (
--     `INCOME_DETAILS_INFO_ID` bigint      NOT NULL    GENERATED BY DEFAULT AS IDENTITY,
--     `INCOME_DETAILS_CD` varchar(30),
--     `INCOME_DETAILS_NM` varchar(30),
--     PRIMARY KEY (`INCOME_DETAILS_INFO_ID`)
-- );
--
-- CREATE TABLE `INCOME_DEDUCTION`
-- (
--     `INCOME_DEDUCTION_ID`           bigint      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
--     `MEMBER_KEY`                    bigint      NOT NULL,
--     `INCOME_SEPARATE_INFO_ID`       bigint      NOT NULL ,
--     `INCOME_DEDUCTION_AMT`          varchar(100),
--     PRIMARY KEY (`INCOME_DEDUCTION_ID`)
-- );
--
-- CREATE TABLE `INCOME`
-- (
--     `INCOME_ID`                     bigint      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
--     `MEMBER_KEY`                    bigint      NOT NULL,
--     `COMPANY_ID`                    bigint      NOT NULL ,
--     `INCOME_DETAILS_INFO_ID`        bigint      NOT NULL ,
--     `INCOME_SEPARATE_INFO_ID`       bigint      NOT NULL ,
--     `INCOME_AMT`                 varchar(100),
--     PRIMARY KEY (`INCOME_ID`)
-- );
--
-- CREATE TABLE `EMPLOYEE`
-- (
--     `EMPLOYEE_ID`       bigint      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
--     `MEMBER_KEY`        bigint      NOT NULL,
--     `COMPANY_ID`        bigint      NOT NULL ,
--     `PAY_DT`            date,
--     `JOIN_DT`           date,
--     `RETIRE_DT`         date,
--     PRIMARY KEY (`EMPLOYEE_ID`)
-- );
--
-- CREATE TABLE `COMPANY`
-- (
--     `COMPANY_ID`                    bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
--     `COMPANY_CD`                    varchar(30) unique,
--     `CORPORATE_REGISTRATION_NO`     varchar(30) unique,
--     `COMPANY_NAME`                  varchar(100),
--     PRIMARY KEY (`COMPANY_ID`)
-- );
--
-- CREATE TABLE `APP_INFO`
-- (
--     `APP_INFO_ID`           bigint      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
--     `APP_VER`               varchar(30),
--     `PRODUCTION_COMPANY_NM` varchar(30),
--     `APP_SVC_CD`            varchar(30),
--     `APP_HOST_NM`           varchar(30),
--     `WORKER_RES_DT`         date,
--     `WORKER_REQ_DT`         date,
--     PRIMARY KEY (APP_INFO_ID)
-- );
--
--







